import { SITE_URL } from "@/lib/site";
import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: [
          "Googlebot",
          "Googlebot-Image",
          "Googlebot-News",
          "Googlebot-Video",
          "Bingbot",
          "Slurp",
          "DuckDuckBot",
          "Baiduspider",
          "YandexBot",
          "Applebot",
          "facebot",
          "ia_archiver",
        ],
        allow: "/",
        crawlDelay: 1,
      },
      {
        userAgent: [
          "AhrefsBot",
          "SemrushBot",
          "MJ12bot",
          "DotBot",
          "BLEXBot",
          "DataForSeoBot",
          "PetalBot",
          "Bytespider",
          "GPTBot",
          "ChatGPT-User",
          "CCBot",
          "anthropic-ai",
          "Claude-Web",
          "cohere-ai",
          "Omgilibot",
          "Omgili",
          "FacebookBot",
          "FacebookExternalHit",
          "Amazonbot",
          "SeznamBot",
          "ImagesiftBot",
          "YouBot",
          "Scrapy",
          "python-requests",
          "go-http-client",
          "curl",
          "wget",
          "HTTrack",
          "WebCopier",
          "WebReaper",
          "WebStripper",
          "Offline Explorer",
          "Teleport",
          "TeleportPro",
          "WebZIP",
          "linko",
          "HTTrack",
          "Microsoft.URL.Control",
          "Xenu",
          "larbin",
          "libwww",
          "ZyBORG",
          "Download Ninja",
          "grub-client",
          "k2spider",
          "NPBot",
          "WebReaper",
          "WebSauger",
          "WebStripper",
          "WebZip",
          "Octopus",
          "Navroad",
          "NearSite",
          "NetAnts",
          "Mister PiX",
          "tAkeOut",
          "WebAuto",
          "WebBandit",
          "WebCopier",
          "WebEnhancer",
          "WebSite Quester",
          "WebStripper",
          "WebZIP",
          "Widow",
          "WWWOFFLE",
          "Xaldon WebSpider",
          "Zeus",
          "RepoMonkey",
          "SiteSucker",
          "Crescent",
          "CherryPicker",
          "EmailCollector",
          "EmailSiphon",
          "EmailWolf",
          "ExtractorPro",
          "CopyRightCheck",
          "WebmasterWorldForumBot",
          "SurveyBot",
          "Nutch",
          "proximic",
          "changedetection",
          "WeSEE:Search",
          "SearchmetricsBot",
          "OrangeBot",
          "spbot",
          "SEOkicks",
          "DomainCrawler",
          "archive.org_bot",
        ],
        disallow: "/",
      },
      {
        userAgent: "*",
        allow: "/",
        crawlDelay: 2,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
