export const CITATION_CRAWLERS = [
  "OAI-SearchBot",
  "ChatGPT-User",
  "Claude-SearchBot",
  "Claude-User",
  "PerplexityBot",
  "Perplexity-User",
];

export const SEARCH_CRAWLERS = [
  "Googlebot",
  "Googlebot-Image",
  "Googlebot-News",
  "Googlebot-Video",
  "Bingbot",
  "Slurp",
  "DuckDuckBot",
  "Baiduspider",
  "YandexBot",
  "Applebot",
  "facebot",
  "ia_archiver",
];

export const BLOCKED_CRAWLERS = [
  "AhrefsBot",
  "SemrushBot",
  "MJ12bot",
  "DotBot",
  "BLEXBot",
  "DataForSeoBot",
  "PetalBot",
  "Bytespider",
  "GPTBot",
  "ClaudeBot",
  "CCBot",
  "anthropic-ai",
  "Claude-Web",
  "cohere-ai",
  "Omgilibot",
  "Omgili",
  "FacebookBot",
  "FacebookExternalHit",
  "Amazonbot",
  "SeznamBot",
  "ImagesiftBot",
  "YouBot",
  "Scrapy",
  "python-requests",
  "go-http-client",
  "curl",
  "wget",
  "HTTrack",
  "WebCopier",
  "WebReaper",
  "WebStripper",
  "Offline Explorer",
  "Teleport",
  "TeleportPro",
  "WebZIP",
  "linko",
  "Microsoft.URL.Control",
  "Xenu",
  "larbin",
  "libwww",
  "ZyBORG",
  "Download Ninja",
  "grub-client",
  "k2spider",
  "NPBot",
  "WebSauger",
  "WebZip",
  "Octopus",
  "Navroad",
  "NearSite",
  "NetAnts",
  "Mister PiX",
  "tAkeOut",
  "WebAuto",
  "WebBandit",
  "WebEnhancer",
  "WebSite Quester",
  "Widow",
  "WWWOFFLE",
  "Xaldon WebSpider",
  "Zeus",
  "RepoMonkey",
  "SiteSucker",
  "Crescent",
  "CherryPicker",
  "EmailCollector",
  "EmailSiphon",
  "EmailWolf",
  "ExtractorPro",
  "CopyRightCheck",
  "WebmasterWorldForumBot",
  "SurveyBot",
  "Nutch",
  "proximic",
  "changedetection",
  "WeSEE:Search",
  "SearchmetricsBot",
  "OrangeBot",
  "spbot",
  "SEOkicks",
  "DomainCrawler",
  "archive.org_bot",
];
