packages:
  - .

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  "cross-spawn": "7.0.6"
  "glob": "13.0.1"
  "tar": "7.5.7"
  "ws": "^8.21.0"
  "brace-expansion": "^5.0.8"
  "minimatch@3>brace-expansion": "^1.1.12"
  "postcss": "^8.5.22"
  "next>sharp": "^0.35.4"
